server {
        server_name ultradent66.ru;

        ssl_certificate /etc/nginx/certs/ultradent66.ru.pem;
        ssl_certificate_key /etc/nginx/certs/ultradent66.ru-key.pem;

        location ~ ^/manager/.* {
            return 301 $scheme://ultradent72.ru$request_uri;
        }

        include settings.conf;
}