server {
        server_name ultradent72.ru;

        ssl_certificate /etc/nginx/certs/ultradent72.ru.pem;
        ssl_certificate_key /etc/nginx/certs/ultradent72.ru-key.pem;

        include settings.conf;
}